version: '3'
services:
  back:
    image: solyyy/dockerback:latest
    ports:
      - "5000:5000"
    environment:
      - CURRENT_ENVIRONMENT=development
    container_name: docker-back

  front:
    image: solyyy/dockerfront:latest
    ports:
      - "8080:80"
    environment:
      - WS_BACK_URL=http://localhost:5000
    container_name: docker-front

